version: "3.7"

networks:
  haproxy:

services:
  haproxy:
    image: haproxy:2.0.25
    container_name: haproxy
    ports:
      - "80:80"
      - "2080:2080"
    networks:
      - haproxy
    volumes: 
      - ./config/haproxy:/usr/local/etc/haproxy
    depends_on:
      - webserver-01
      - webserver-02
      - webserver-03

  webserver-01:
    image: nginx
    container_name: webserver-01
    ports:
      - "8080:80"
    volumes: 
      - ./config/nginx/whoami.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80 
    networks:
      - haproxy

  
  webserver-02:
    image: nginx
    container_name: webserver-02
    ports:
      - "8081:80"
    volumes: 
      - ./config/nginx/whoami.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    networks:
      - haproxy

  webserver-03:
    image: nginx
    container_name: webserver-03
    ports:
      - "8082:80"
    volumes: 
      - ./config/nginx/whoami.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    networks:
      - haproxy